select * from nnathan.DIQdata
sp_rename 'nnathan.DIQdata.DIQ010', 'Doctor told you have diabetes', 'COLUMN'
sp_rename 'nnathan.DIQdata.DID040', 'Age when you first had diabetes', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ160', 'Ever told you had prediabetes', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ170', 'Ever told you have a health risk for diabetes', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ172', 'Feel could be at risk for diabetes', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ180', 'Had blood test past 3 years', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ050', 'Taking insulin now', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ070', 'Take diabetic pills to lower blood sugar', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ230', 'How long ago saw a diabetes specialist', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ240', 'Is there one Dr you see for diabetes', 'COLUMN'
sp_rename 'nnathan.DIQdata.DID250', 'Past year how many times seen doctor', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ275', 'Past year Dr checked for A1C', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ280', 'What was your last A1C level', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ291', 'What does Dr say A1C level should be', 'COLUMN'
sp_rename 'nnathan.DIQdata.DID320', 'What was your recent LDL number', 'COLUMN'
sp_rename 'nnathan.DIQdata.DID330', 'What does doctor say LDL should be', 'COLUMN'
sp_rename 'nnathan.DIQdata.DID341', 'Past year times Dr check feet for sores', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ360', 'Last time had pupils dilated for exam', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ080', 'Diabetes affected eyes/had retinopathy', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ175', 'Reason feel/told at risk', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ060', 'How often taking insulin', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ260', 'How often check blood for glucose/sugar', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ300', 'What was your recent BP', 'COLUMN'
sp_rename 'nnathan.DIQdata.DID310', 'What does Dr say BP should be', 'COLUMN'
sp_rename 'nnathan.DIQdata.DIQ350', 'How often check your feet', 'COLUMN'

