library('RODBC')
myconn=RODBC::odbcConnect('QBS181','nnathan','nnathan@qbs181')
#install.packages('sqldf')
library(sqldf)
library(dbplyr)
R_Flowsheets=sqlQuery(myconn, "select * from Flowsheets")
R_Flowsheets$DISP_NAME=sapply(R_Flowsheets$DISP_NAME,function(x)gsub("cc/kg","CC-Kg",x))
R_Flowsheets=sapply(R_Flowsheets,function(x)gsub(pattern = "[[:alnum:]]", replacement = " ",x))
R_Provider=sqlQuery(myconn, "select * from Provider")
install.packages("tidyr")
library(tidyr)
R_Provider2=data.frame(extract(R_Provider, NEW_PROV_NAME, c("LastName", "FirstName"), "(\\w+),\\s(\\w+)"))
grep(pattern='^Wa',R_Provider2$LastName, value=TRUE)
